# Generated by Django 2.2.23 on 2021-05-29 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('value', models.IntegerField()),
                ('approx_time', models.IntegerField()),
                ('employer', models.CharField(max_length=50)),
                ('date', models.TimeField(default=datetime.datetime(2016, 9, 30, 0, 0))),
                ('description', models.CharField(default='برای مشتری های از نوع y نیاز دارم تا آمار x رو به دست بیارم.', max_length=500)),
            ],
        ),
    ]
