# Generated by Django 2.2.23 on 2021-05-30 14:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_newuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='last_login',
            field=models.TimeField(default=datetime.datetime(2021, 5, 30, 14, 6, 9, 553880, tzinfo=utc)),
        ),
    ]
