# Generated by Django 2.2.23 on 2021-05-30 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_newuser_last_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewUser',
        ),
    ]
