# Generated by Django 2.2.23 on 2021-06-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20210601_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='assigned_user',
            field=models.CharField(default='', max_length=50),
        ),
    ]
