# Generated by Django 2.2.23 on 2021-06-03 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_job_assigned_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.NewUser')),
            ],
        ),
    ]
